/// Print zsh shell integration commands.
pub fn zsh() {
    // Adapted from:
    // https://github.com/gsamokovarov/jump/blob/main/shell/zsh.go
    let out = "# Put the line below in ~/.zshrc:
#
#   eval \"$(jump --shell zsh)\"
#
# The following lines are autogenerated:
__jump_chpwd() {
  jump --chdir
}

j() {
  # Note early return if jump fails
  local dir=\"$(jump $@)\" || return
  test -d \"$dir\" && cd \"$dir\"
}

typeset -gaU chpwd_functions
chpwd_functions+=__jump_chpwd";

    println!("{}", out);
}
